name: Build and Deploy to Google Cloud Storage

on:
  push:
    branches:
    - main
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v3
          - name: Check out repository
            run: ls -lah $GITHUB_WORKSPACE
          - name: Upload google-cloud-storage
            uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@v0
            with:
              path: ${{ github.workspace }}
              destination: natural-design.work
              credentials: ${{ secrets.GCP_CREDENTIALS }}