name: Build and Deploy to Google Cloud Storage
 
on:
  push:
    branches:
    - main
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v3
          - name: Check out repository
            run: ls -lah $GITHUB_WORKSPACE
          - id: 'upload-file'
            uses: 'google-github-actions/upload-cloud-storage@v1'
            with:
              path: '/path/to/file'
              destination: 'bucket-name/file'