name: Build and Deploy to Google Cloud Storage
 
on:
  push:
    branches:
    - main
jobs:
  job:
    runs-on: ubuntu-latest
  steps:
      - name: Check out repository
      - uses: actions/checkout@v2
        run: ls -lah $GITHUB_WORKSPACE
      - name: Upload google-cloud-storage
        uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
        with:
          path: ${{ github.workspace }}
          destination: natural-design.work
          credentials: ${{ secrets.GCP_CREDENTIALS }}